---
development:
  cloud_name: hijbpeqlx
  api_key: '446471589138777'
  api_secret: ODLjFi9X0iDeQK593AMGyHvXsIg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hijbpeqlx
  api_key: '446471589138777'
  api_secret: ODLjFi9X0iDeQK593AMGyHvXsIg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hijbpeqlx
  api_key: '446471589138777'
  api_secret: ODLjFi9X0iDeQK593AMGyHvXsIg
  enhance_image_tag: true
  static_image_support: false
